name: Cache Go Modules
description: Sets Up Go Module Caching
branding:
  icon: save
  color: blue
runs:
  using: composite
  steps:
    # See https://github.com/actions/cache/blob/main/examples.md#linux-1
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
